{
  "formatVersion": "1.1",
  "component": {
    "group": "com.austen.abc-aop-plugin",
    "module": "abc-aop-plugin",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "abc-aop-plugin-1.0.9.jar",
          "url": "abc-aop-plugin-1.0.9.jar",
          "size": 18377,
          "sha512": "4865bcb804c60b095893758a35796ad8c1c13d6ec79cfec5e5dd07d574b390441446ffa57d964f80f72da266e44dcacaa40029b68d0eb4d70ff00535554887b2",
          "sha256": "59fdecfa8aa73adea1a99ad426adaef5f4fba2189ed5e0196f84818a1f4bd286",
          "sha1": "7c6a0ff5a38a107b6304f012d6e29c4005c40832",
          "md5": "aa14eb0648457048428ba363c73fea65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.8.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "abc-aop-plugin-1.0.9.jar",
          "url": "abc-aop-plugin-1.0.9.jar",
          "size": 18377,
          "sha512": "4865bcb804c60b095893758a35796ad8c1c13d6ec79cfec5e5dd07d574b390441446ffa57d964f80f72da266e44dcacaa40029b68d0eb4d70ff00535554887b2",
          "sha256": "59fdecfa8aa73adea1a99ad426adaef5f4fba2189ed5e0196f84818a1f4bd286",
          "sha1": "7c6a0ff5a38a107b6304f012d6e29c4005c40832",
          "md5": "aa14eb0648457048428ba363c73fea65"
        }
      ]
    }
  ]
}
