{
  "formatVersion": "1.1",
  "component": {
    "group": "com.austen.abc-aop-plugin",
    "module": "abc-aop-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "abc-aop-plugin-1.0.0.jar",
          "url": "abc-aop-plugin-1.0.0.jar",
          "size": 1588,
          "sha512": "e20cc1de65544797b8124af10c2d05f992a12511c03ca5f18eceeece3d419311d973cb771560404fb105198b7a36cb85b87cb904d498d743a8a6bd53d0f88266",
          "sha256": "d7532bd4f2a270b6ccc4a3677c0566a62df9ea4bf453b08fc03d3d1fc052909d",
          "sha1": "633c052c0606c3485ca22d029ab0b18f4cbf4720",
          "md5": "af06bf4bd0db35759997e6ed6e35e4b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "abc-aop-plugin-1.0.0.jar",
          "url": "abc-aop-plugin-1.0.0.jar",
          "size": 1588,
          "sha512": "e20cc1de65544797b8124af10c2d05f992a12511c03ca5f18eceeece3d419311d973cb771560404fb105198b7a36cb85b87cb904d498d743a8a6bd53d0f88266",
          "sha256": "d7532bd4f2a270b6ccc4a3677c0566a62df9ea4bf453b08fc03d3d1fc052909d",
          "sha1": "633c052c0606c3485ca22d029ab0b18f4cbf4720",
          "md5": "af06bf4bd0db35759997e6ed6e35e4b0"
        }
      ]
    }
  ]
}
